//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ledReport.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class siixsem_led_rpt_dbEntities : DbContext
    {
        public siixsem_led_rpt_dbEntities()
            : base("name=siixsem_led_rpt_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int getDetail()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("getDetail");
        }
    
        public virtual int getLastDay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("getLastDay");
        }
    }
}
